plugins {
    id 'java'
}

group = 'org.openjdk'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

configurations {
    // include in jar
    classpath
}

dependencies {
    classpath 'net.sf.jopt-simple:jopt-simple:4.9'
    testImplementation 'junit:junit:4.11'
    configurations.implementation.extendsFrom(configurations.classpath)
}

tasks.named('jar') {
    archiveBaseName.set('bytestacks')
    archiveClassifier.set('')
    archiveVersion.set('')
    from {
        configurations.classpath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
