#!/bin/bash
cd "${0%/*}"
file=$1
shift
${JAVA_HOME}/bin/java -Xss16m -cp build/libs/bytestacks-1.0-SNAPSHOT.jar org.openjdk.Bytestacks $* $file <&0 > $file.stacks

if [ $? -eq 0 ]
then
  # Download and run FlameGraph
  if [ ! -d FlameGraph ] ; then
    git clone https://github.com/brendangregg/FlameGraph.git
  fi
  FlameGraph/flamegraph.pl --cp $file.stacks > $file.svg
fi

