#!/bin/bash
cd "${0%/*}"
file=$1
shift
${JAVA_HOME}/bin/java -Xss16m -cp build/libs/bytestacks-1.0-SNAPSHOT.jar org.openjdk.Bytestacks $* $file <&0 > $file.stacks

if [ $? -eq 0 ]
then
  flamegraph=FlameGraph/flamegraph.pl
  if [ ! -x "${flamegraph}" ] ; then
    if [ -e FlameGraph ] ; then
      echo "FlameGraph exists but ${flamegraph} is missing or not executable" >&2
      exit 1
    fi
    if ! git clone --depth 1 https://github.com/brendangregg/FlameGraph.git FlameGraph ; then
      echo "Unable to download FlameGraph; clone it into $(pwd)/FlameGraph or use a bundle that includes it" >&2
      exit 1
    fi
  fi
  "${flamegraph}" --cp $file.stacks > $file.svg
fi
